### ISSUE TITLE
Video not loading

### ISSUE THREAD

**Issue by iamsatyajit05** [CapSoftware/Cap#47]
I recorded a video, but after recording I am not able to load it.

HLS error: {type: 'networkError', details: 'manifestLoadError', fatal: true, url: 'https://cap.so/api/playlist?userId=5fyy6sa6zm40dje&videoId=x7k574anznfj7wk&videoType=master', loader: sO, …}context: {id: null, level: 0, responseType: 'text', type: 'manifest', url: 'https://cap.so/api/playlist?userId=5fyy6sa6zm40dje&videoId=x7k574anznfj7wk&videoType=master', …}details: "manifestLoadError"error: Error: A network error (status 500) occurred while loading manifest
    at tn.handleNetworkError (https://cap.so/_next/static/chunks/9bfae678-cd5f2e1cf063d8ed.js:1:45767)
    at Object.onError (https://cap.so/_next/static/chunks/9bfae678-cd5f2e1cf063d8ed.js:1:43740)
    at sO.readystatechange (https://cap.so/_next/static/chunks/9bfae678-cd5f2e1cf063d8ed.js:15:32712)message: "A network error (status 500) occurred while loading manifest"stack: "Error: A network error (status 500) occurred while loading manifest\n    at tn.handleNetworkError (https://cap.so/_next/static/chunks/9bfae678-cd5f2e1cf063d8ed.js:1:45767)\n    at Object.onError (https://cap.so/_next/static/chunks/9bfae678-cd5f2e1cf063d8ed.js:1:43740)\n    at sO.readystatechange (https://cap.so/_next/static/chunks/9bfae678-cd5f2e1cf063d8ed.js:15:32712)"[[Prototype]]: Objectfatal: trueloader: sO {xhrSetup: null, requestTimeout: 210, retryTimeout: 208, retryDelay: 1000, config: {…}, …}networkDetails: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}response: {url: 'https://cap.so/api/playlist?userId=5fyy6sa6zm40dje&videoId=x7k574anznfj7wk&videoType=master', data: undefined, code: 500, text: ''}stats: G {aborted: false, loaded: 52, retry: 1, total: 0, chunkCount: 0, …}type: "networkError"url: "https://cap.so/api/playlist?userId=5fyy6sa6zm40dje&videoId=x7k574anznfj7wk&videoType=master"[[Prototype]]: Object

This is log from console :)

**Comment by richiemcilroy** [comment]
Thanks for this @iamsatyajit05 - looking into it :)
